[project]
name = "decentralized-content-monetization"
description = "Blockchain project: decentralized-content-monetization"
authors = ["Automated Builder <automation@blockchain.dev>"]
telemetry = false
cache_dir = ".clarinet"
requirements = []

[contracts.content-tokenization-vault]
path = "contracts/content-tokenization-vault.clar"
depends_on = []

[contracts.creator-revenue-distributor]
path = "contracts/creator-revenue-distributor.clar"
depends_on = []

